DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS things;
DROP TABLE IF EXISTS stars;

CREATE TABLE users (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  date_created TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE things (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  thing JSON NOT NULL,
  date_created TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE stars (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  thing_id BIGINT NOT NULL REFERENCES things(id) ON DELETE CASCADE,
  date_created TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
